.TH MYCAT 1 "September 2026" "v0.4.1" "User Commands"
.SH NAME
mycat \- custom utility/function to process files
.SH SYNOPSIS
.B mycat
[\-options] [\fIfile...\fR]
.SH DESCRIPTION
.B mycat
reads files sequentially, writing them to standard output. It is implemented as part of the operating system assignment client application.
.SH OPTIONS
.TP
\fB\-h\fR
Display help message and exit.
.SH AUTHOR
Saneela Aziz <your_email@example.com>
.TH MYCAT 1 "2026-09-23" "V0.4.1" "User Commands" 
.SH NAME
mycat \- custom file viewing and processing utility
.SH SYNOPSIS
.B mycat
[\fIOPTION\fR]...[\fIFILE\fR]...
.SH DESCRIPTION
.B mycat
is a client application that reads files sequentially and writes them to standard output.
.SH OPTIONS
.TP
Display help message and exit. 
.SH AUTHOR
Written by Saneela Aziz <saneela.aziz@example.com>.
